pipeline {
    agent any 
     stages {
        stage('Example') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "luffy,naruto"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr kakashi', description: 'Who should I greet ?')
                }
            }
            steps {
                echo "Hello, ${PERSON}, Suup buddy."
            }
        }
    }
          stage('modified') {
            steps {
                echo 'new stage test passed ' 
            }
          }
    }
}
